<?php
    $response = '{
      "returnCode": "O",
      "returnMsg": "API success",
      "detail": [
        [
          {
            "ID_NO": "L29323061F",
            "POS_ID": "",
            "POSITION_FULL_NAME": "經理",
            "EMPLOYEE_ID": "L107770S6K",
            "DIV_FULL_NAME": "資資訊湖人事行政資訊科",
            "SRC": "C",
            "SEX": "1",
            "INSTITUTION_PHONE1": "02",
            "INSTITUTION_PHONE2": "0227551399",
            "EMAIL": "XXXXX@cathlife.com.tw",
            "NICK_NAME": "",
            "AREA_CODE": "TW-O1",
            "STATUS_NAME": "改新",
            "SUP_DIV_NO": "",
            "INSTITUTION_PHONE3": "26900",
            "DIV_SHORT_NAME": "人事資訊科",
            "POSITION": "41",
            "EMP_NAME": "陳o丹",
            "VR_DIV": "",
            "EMP_RMK": "",
            "LOGIN_ID": "L10777096K",
            "ASSIGN_CODE": "2",
            "NTL_TYPE": "L",
            "POSITION_NAME": "經理",
            "CATHAY_NO": "00511960",
            "PAR_CODE": "0",
            "USER_CATHAY_ID": "A003",
            "COMP_NAME": "國泰人壽",
            "ENG_LNM": "BoR JOU",
            "OLD_CATHAY_NO": "AOL10777096K",
            "ENG_MNM": "",
            "NTL_CODE": "TW",
            "ENG_FNM": "CHoN",
            "MARY": "l",
            "COMP_ID": "C0",
            "STS_RMK": "",
            "DIV_NO": "07C0000",
            "POS_RANK": "",
            "CELLULAR_PHONE": "0916125456",
            "DEGREE": ""
          }
        ],
        [
          {
            "ID_NO": "A12658449A",
            "POS_ID": "",
            "POSITION_FULL_NAME": "經理",
            "EMPLOYEE_ID": "L107770S6K",
            "DIV_FULL_NAME": "資資訊湖人事行政資訊科",
            "SRC": "C",
            "SEX": "1",
            "INSTITUTION_PHONE1": "02",
            "INSTITUTION_PHONE2": "0227551399",
            "EMAIL": "XXXXX@cathlife.com.tw",
            "NICK_NAME": "",
            "AREA_CODE": "TW-O1",
            "STATUS_NAME": "改新",
            "SUP_DIV_NO": "",
            "INSTITUTION_PHONE3": "26900",
            "DIV_SHORT_NAME": "人事資訊科",
            "POSITION": "132",
            "EMP_NAME": "陳o丹",
            "VR_DIV": "",
            "EMP_RMK": "",
            "LOGIN_ID": "L10777096K",
            "ASSIGN_CODE": "2",
            "NTL_TYPE": "L",
            "POSITION_NAME": "經理",
            "CATHAY_NO": "00000006",
            "PAR_CODE": "0",
            "USER_CATHAY_ID": "A003",
            "COMP_NAME": "國泰人壽",
            "ENG_LNM": "BoR JOU",
            "OLD_CATHAY_NO": "AOL10777096K",
            "ENG_MNM": "",
            "NTL_CODE": "TW",
            "ENG_FNM": "CHoN",
            "MARY": "l",
            "COMP_ID": "C0",
            "STS_RMK": "",
            "DIV_NO": "07C0000",
            "POS_RANK": "",
            "CELLULAR_PHONE": "0916125456",
            "DEGREE": ""
          }
        ]
      ],
      "UUID": ""
    }
    ';
    die($response);
